# image: node:latest

# pages:
#   stage: deploy
#   cache:
#     paths:
#       - node_modules/
#   script:
#     - npm install
#     - npm run build
#     - rm -rf public
#     - cp build/index.html build/404.html
#     - mv build public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master

image: node:latest

variables:
  PUBLIC_URL: /

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - npm install
    - npm run build
    - rm -rf public
    - cp build/index.html build/404.html
    - mv build public
    # - npm install        # Install all dependencies
    # - npm run build      # Build for prod
    # - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    # - mv build public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
    - public

  only:
    - main